### PR TITLE
Added eslint, prettier

### PR DESCRIPTION
**Pull request by mizhstreet**

### CODE REVIEW

**Comment by tkeiyama** [comment]
@mizhstreet 

Thanks for the pull request!

Here are what I want you to modify for the changes.

First of all, this repository is gonna use [eslint-config-standard-with-typescript](https://www.npmjs.com/package/eslint-config-standard-with-typescript) for the core lint rules, instead of `@typescript-eslint/recommended`. And all eslint plugins/config this repository is gonna use are as following:
```
  "eslint-config-prettier": "^8.1.0",
  "eslint-config-standard": "^16.0.2",
  "eslint-config-standard-with-typescript": "^20.0.0",
  "eslint-plugin-import": "^2.22.1",
  "eslint-plugin-node": "^11.1.0",
  "eslint-plugin-prettier": "^3.3.1",
  "eslint-plugin-promise": "^5.1.0",
  "eslint-plugin-simple-import-sort": "^7.0.0",
  "eslint-plugin-sort-destructure-keys": "^1.3.5",
  "eslint-plugin-standard": "^5.0.0",
  "eslint-plugin-tsdoc": "^0.2.11",
  "eslint-plugin-typescript-sort-keys": "^1.6.0",
```

We are gonna use jest for testing functions, but for now, we don't need it.

Second of all, the prettier rules are as following:
```
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: false,
  singleQuote: false,
  quoteProps: 'as-needed',
  trailingComma: 'all',
  bracketSpacing: true,
  arrowParens: 'always',
  rangeStart: 0,
  rangeEnd: Infinity,
  requirePragma: false,
  insertPragma: false,
  proseWrap: 'preserve',
  endOfLine: 'lf',
```

Third of all, could you write a script for eslint.

Thanks.

**Comment by tkeiyama** [comment]
@mizhstreet 

Thanks for the pull request!

Here are what I want you to modify for the changes.

First of all, this repository is gonna use [eslint-config-standard-with-typescript](https://www.npmjs.com/package/eslint-config-standard-with-typescript) for the core lint rules, instead of `@typescript-eslint/recommended`. And all ESLintplugins/config this repository is gonna use are as follows:
```
  "eslint-config-prettier",
  "eslint-config-standard",
  "eslint-config-standard-with-typescript",
  "eslint-plugin-import",
  "eslint-plugin-node",
  "eslint-plugin-prettier",
  "eslint-plugin-promise",
  "eslint-plugin-simple-import-sort",
  "eslint-plugin-sort-destructure-keys",
  "eslint-plugin-standard",
  "eslint-plugin-tsdoc",
  "eslint-plugin-typescript-sort-keys",
```

We are gonna use jest for testing functions, but for now, we don't need it.

Second of all, the prettier rules are as follows:
```
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: false,
  singleQuote: false,
  quoteProps: 'as-needed',
  trailingComma: 'all',
  bracketSpacing: true,
  arrowParens: 'always',
  rangeStart: 0,
  rangeEnd: Infinity,
  requirePragma: false,
  insertPragma: false,
  proseWrap: 'preserve',
  endOfLine: 'lf',
```

Third of all, could you write a script for the ESLint.

Thanks.

**Comment by tkeiyama** [comment]
@mizhstreet 

Are you working on this?
lmk if you have any updates for this pull request.

**Comment by mizhstreet** [comment]
I'm sorry i've been busy these days. Just want to let you know that i'm still working on it. I'll give you an update soon.

**Comment by tkeiyama** [comment]
@mizhstreet Thanks for your reply. I didn't mean to rush you, so feel free to work on this :D

**Comment by tkeiyama** [comment]
https://prettier.io/docs/en/integrating-with-linters.html

**Comment by mizhstreet** [comment]
Sorry but somehow I couldn't get it to work on my vscode!

**Comment by tkeiyama** [comment]
All good though, Would you still try to work on this?

**Comment by tkeiyama** [comment]
I close this issue for now. You can freely open this issue again!

**Pull request closed without merging**
